"""Add missing product fields

Revision ID: c596478fbf72
Revises: 45d83ce6a4d8
Create Date: 2026-01-03 22:23:05.857850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c596478fbf72'
down_revision = '45d83ce6a4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='inquiry_status', native_enum=False), server_default='new', nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('ix_contacts_email', ['email'], unique=False)
        batch_op.create_index('ix_contacts_status', ['status'], unique=False)

    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.create_index('ix_faqs_category', ['category'], unique=False)

    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.create_index('ix_newsletters_email', ['email'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index('ix_team_members_display_order', ['display_order'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=120), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('session_type', sa.Enum('FREE_INTRO', 'PAID', name='session_type', native_enum=False), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('session_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='booking_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_bookings_scheduled_at', ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=120), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_reviews_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_name')
        batch_op.create_index('ix_categories_name', ['name'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('shipping_charges', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.Enum('PENDING', 'INITIATED', 'PAID', 'FAILED', 'REFUNDED', name='payment_status', native_enum=False), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_address_line1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shipping_address_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('carrier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='order_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('method', sa.Enum('RAZORPAY', 'UPI', 'CARD', 'NETBANKING', 'WALLET', name='payment_method', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('error_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('error_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum', native_enum=False),
               existing_nullable=False)
        batch_op.create_index('ix_payments_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_payments_razorpay_order_id', ['razorpay_order_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('mode')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('main_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('benefits', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nutrition_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('usage_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['sku'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_line1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), server_default='customer', nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('is_active')
        batch_op.drop_column('role')
        batch_op.drop_column('country')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')
        batch_op.drop_column('phone')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sku')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('is_active')
        batch_op.drop_column('weight')
        batch_op.drop_column('usage_instructions')
        batch_op.drop_column('nutrition_info')
        batch_op.drop_column('benefits')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('main_image')
        batch_op.drop_column('images')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.drop_index('ix_payments_razorpay_order_id')
        batch_op.drop_index('ix_payments_order_id')
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('paid_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('error_description')
        batch_op.drop_column('error_code')
        batch_op.drop_column('method')
        batch_op.drop_column('razorpay_signature')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('currency')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='order_status', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('notes')
        batch_op.drop_column('carrier')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('shipping_country')
        batch_op.drop_column('shipping_postal_code')
        batch_op.drop_column('shipping_state')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address_line2')
        batch_op.drop_column('shipping_address_line1')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('shipping_charges')
        batch_op.drop_column('subtotal')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_name')
        batch_op.create_index('ix_categories_name', ['name'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_user_id')
        batch_op.drop_index('ix_reviews_product_id')

    op.drop_table('reviews')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index('ix_bookings_scheduled_at')

    op.drop_table('bookings')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index('ix_team_members_display_order')

    op.drop_table('team_members')
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_index('ix_newsletters_email')

    op.drop_table('newsletters')
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_index('ix_faqs_category')

    op.drop_table('faqs')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('ix_contacts_status')
        batch_op.drop_index('ix_contacts_email')

    op.drop_table('contacts')
    # ### end Alembic commands ###
